// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class AuditLog
{
    public Guid LogId { get; set; }

    public decimal UserId { get; set; }

    public string TableName { get; set; }

    public string ColumnName { get; set; }

    public string PreviousData { get; set; }

    public string NewData { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual User User { get; set; }
}