// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class ConvertedUrl
{
    public string GuildId { get; set; }

    public string ChannelId { get; set; }

    public string MessageId { get; set; }

    public string UserId { get; set; }

    public string OriginalUrl { get; set; }

    public DateTime DatePosted { get; set; }

    public virtual Guild Guild { get; set; }

    public virtual User User { get; set; }
}