// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class GameType
{
    public Guid GameTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Game> Games { get; set; } = new List<Game>();
}