// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class Game
{
    public Guid GameId { get; set; }

    public Guid GameTypeId { get; set; }

    public string GuildId { get; set; }

    public string GameData { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual GameType GameType { get; set; }

    public virtual ICollection<GameUser> GameUsers { get; set; } = new List<GameUser>();

    public virtual Guild Guild { get; set; }
}