// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class Job
{
    public int JobId { get; set; }

    public string JobTitle { get; set; }

    public decimal PayMin { get; set; }

    public decimal PayMax { get; set; }

    public int Cooldown { get; set; }

    public short RiskLevel { get; set; }

    public double Probability { get; set; }
}