// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class Setting
{
    public Guid SettingId { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }
}