// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class User
{
    public decimal UserId { get; set; }

    public decimal Balance { get; set; }

    public bool Banned { get; set; }

    public DateTime? DailyCooldown { get; set; }

    public virtual ICollection<ConvertedUrl> ConvertedUrls { get; set; } = new List<ConvertedUrl>();
}