// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class User
{
    public string UserId { get; set; }

    public decimal Balance { get; set; }

    public bool Banned { get; set; }

    public virtual ICollection<ConvertedUrl> ConvertedUrls { get; set; } = new List<ConvertedUrl>();

    public virtual ICollection<GameUser> GameUsers { get; set; } = new List<GameUser>();

    public virtual UserCooldown UserCooldown { get; set; }

    public virtual UserStat UserStat { get; set; }
}