// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure.InferiorBot;

public partial class UserStat
{
    public decimal UserId { get; set; }

    public decimal AllTimeWon { get; set; }

    public decimal AllTimeLost { get; set; }

    public decimal BiggestWin { get; set; }

    public decimal BiggestLoss { get; set; }

    public decimal DailyCount { get; set; }

    public decimal DailyStreak { get; set; }

    public decimal WorkCount { get; set; }

    public decimal CoinFlipWins { get; set; }

    public decimal CoinFlipLosses { get; set; }

    public decimal GuessWins { get; set; }

    public decimal GuessLosses { get; set; }

    public virtual User User { get; set; }
}